fix: modify husky script hook

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,39 +1,51 @@
-#!usr/bin/sh
+#!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-echo '🏗️👷 Styling, testing, and building your project before committing'
+echo '🏗️👷 Styling, testing and building your project before committing'
 
-# Clean up the eslint and prettier
-npm run lint:fix && npm run prettier && (
-  echo '🧹 Cleaned up the codebase'
+# Run Prettier, ESLint and Type check on your codebase
+echo '🏗️👷 Running Prettier, ESLint and Type check on your codebase'
+npm run lint:fix && npm run prettier || (
+  echo '🤢🤮🤢🤮 Its FOKING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
+        Prettier Check Failed. Run npm run format, add changes and try commit again.';
+
+        false
 )
+
 # Check Prettier standards
 npm run check-format ||
 (
-    echo '🤢🤮🤢🤮 Prettier Check Failed. Please run "npm run format", add changes, and try committing again.'
+    echo '🤢🤮🤢🤮 Its FOKING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
+            Prettier Check Failed. Run npm run format, add changes and try commit again.';
     false;
 )
 
-# Check ESLint standards
+# Check ESLint Standards
 npm run check-lint ||
 (
-    echo '😤 ESLint Check Failed. Make the required changes listed above, add them, and try committing again.'
-    false;
+        echo '😤🏀👋😤 Get that weak shit out of here! 😤🏀👋😤
+                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
+        false;
 )
 
-# Check TypeScript standards
+# Check tsconfig standards
 npm run check-types ||
 (
-    echo '🤡 TypeScript check failed. Fix the type issues and try committing again.'
+    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
+            Are you seriously trying to write that? Make the changes required above.'
     false;
 )
 
-# Build check
+# If everything passes... Now we can commit
+echo '🤔🤔🤔🤔... Alright.... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'
+
 npm run build ||
 (
-    echo '❌ Build failed! Please address the build issues before committing.'
+    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
+            Next build failed: View the errors above to see why.
+    '
     false;
 )
 
-# If everything passes...
-echo '✅ All checks passed. Committing your changes now! ✅'
+# If everything passes... Now we can commit
+echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
